name: vps-edge

services:
  haproxy:
    build: .
    image: vps-edge-haproxy:local
    container_name: vps-edge-haproxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - vps_edge

networks:
  vps_edge:
    name: vps_edge
    external: true
